apiVersion: apps/v1
kind: Deployment
metadata:
  name: strangeloopplatform-api
  labels:
    app: strangeloopplatform-api
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strangeloopplatform-api
  template:
    metadata:
      labels:
        app: strangeloopplatform-api
        version: v1.0.0
    spec:
      containers:
      - name: strangeloopplatform-api
        image: strangeloopplatform:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80;https://+:443"
        - name: AzureOpenAI__Endpoint
          valueFrom:
            secretKeyRef:
              name: strangeloopplatform-secrets
              key: azure-openai-endpoint
        - name: AzureOpenAI__ApiKey
          valueFrom:
            secretKeyRef:
              name: strangeloopplatform-secrets
              key: azure-openai-apikey
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: strangeloopplatform-service
  labels:
    app: strangeloopplatform-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: strangeloopplatform-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strangeloopplatform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.strangeloopplatform.com
    secretName: strangeloopplatform-tls
  rules:
  - host: api.strangeloopplatform.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: strangeloopplatform-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: strangeloopplatform-secrets
type: Opaque
data:
  azure-openai-endpoint: <base64-encoded-endpoint>
  azure-openai-apikey: <base64-encoded-apikey>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: strangeloopplatform-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strangeloopplatform-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 